### ISSUE TITLE
Multiple click on Add expense leads to blank screen.

### ISSUE THREAD

**Issue by Aakashbansal837** [nidhish-srivastava/Expense-Tracker-React#5]
see the shared video for more info.

steps:
1. click on add expense.
2. without filling in any data click on add expense multiple times.
3. blank screen will appear.

https://user-images.githubusercontent.com/30870405/217733193-1d347ccb-c35b-4672-b1e3-653d488e14e5.mov

**Comment by Aakashbansal837** [comment]
this issue might be due to some null state not being handled properly.

**Comment by nidhish-srivastava** [comment]
@Aakashbansal837  go for it as well

**Comment by Aakashbansal837** [comment]
@nidhish-srivastava here's the PR -> https://github.com/nidhish-srivastava/Expense-Tracker-React/pull/7
