### ISSUE TITLE
App should have option to see total monthly expenses.

### ISSUE THREAD

**Issue by Aakashbansal837** [nidhish-srivastava/Expense-Tracker-React#6]
the app should have a total expense view option. otherwise, there is no point in just entering data when you have to calculate that yourself at the end.

<img width="1052" alt="Screenshot 2023-02-09 at 11 55 36 AM" src="https://user-images.githubusercontent.com/30870405/217734597-38c20cc6-be04-4889-ae7a-12a8e396be0a.png">

**Comment by nidhish-srivastava** [comment]
@Aakashbansal837  Solve this issue,great insight though

**Comment by Aakashbansal837** [comment]
@nidhish-srivastava I think first you have to decide where do you want to have that info.

1. is it under all other info
2. near the month tab.

you also have to consider the visibility of the info. whether to show it all the time or only if the info is present.

**Comment by nidhish-srivastava** [comment]
> @nidhish-srivastava I think first you have to decide where do you want to have that info.
> 
> 1. is it under all other info
> 2. near the month tab.
> 
> you also have to consider the visibility of the info. whether to show it all the time or only if the info is present.

Near the month tab
